### ISSUE TITLE
No able to verify the key 

### ISSUE THREAD

**Issue by eric1357a** [mailvelope/keyserver#11]
After I decrypt the link from the email provided by encrypted.asc
The api reply with "Invalid request!"

**Comment by jimc-leones** [comment]
Mee2!  I've attached the decrypted body,
which Mailvelope didn't decrypt (even though it decrypts other test messages encrypted
itself with this key).  The mail reader is Roundcube (roundcubemail-1.1.5-9.1.noarch from
OpenSuSE).  gpg decrypted the body with no hassle.  I extracted the pieces of the
response URL into an editor window and pasted the result (minus line breaks) into Firefox,
plus other attempts e.g. using W3M; the server responded "invalid request" each time
(which is no lie).  

Brainwave: there are an awful lot of 3D digraphs including one in the key ID which is
not authentic.  And in fact, wherever '=' appears legitimately (not including line breaks),
it is followed by 3D, as if you were trying to URL-encode the '=' which should have been 
changed to '%3D'.  When I changed '=3D' wherever occurring to plain '=' the server 
responded "Email address successfully verified!" 

Also I think 'ampersand' needs to be URL-encoded or written as 'ampersand amp semicolon'.
(&amp; let's see if the entity is shown.)  But I've never had the validator barf on equal signs.
I've never attempted using '=\n' as an escaped line break; does that really work?

Attachment link for the decrypted body:
[encrypted.txt](https://github.com/mailvelope/keyserver/files/535298/encrypted.txt)

I'm assuming that the nonce includes a date and won't last forever, and the most a
hacker could do with it is re-verify my key which is already verified.

**Comment by toberndo** [comment]
> Brainwave: there are an awful lot of 3D digraphs including one in the key ID which is
> not authentic. And in fact, wherever '=' appears legitimately (not including line breaks),
> it is followed by 3D, as if you were trying to URL-encode the '=' which should have been 
> changed to '%3D'. When I changed '=3D' wherever occurring to plain '=' the server 
> responded "Email address successfully verified!"
> 
> Also I think 'ampersand' needs to be URL-encoded or written as 'ampersand amp semicolon'.
> (& let's see if the entity is shown.) But I've never had the validator barf on equal signs.
> I've never attempted using '=\n' as an escaped line break; does that really work?

The encoding used is quoted-printable. You can decode for example here: http://www.webatic.com/run/convert/qp.php

I think we should use UTF8 encoding instead to better support manual decryption with GPG for the verification emails.

**Comment by toberndo** [comment]
Here is some info regarding the verification procedure:

If a key is uploaded, it is in a pending verification state. As long as it is not verified, all subsequent uploads of the same key will trigger new verification emails. Only the latest verification emails are valid and previous verification emails will be invalidated by a new key upload. A key in pending verification state can be overwritten by uploading the same key to the server multiple times, but also by uploading a different (maybe newly generated key) with the same email address as the previously uploaded key.

Once a key is verified (with at least one email address), a subsequent upload of the same key or of a key with identical email address will fail. That means for key update on the key server (e.g. after having changed the key by adding another email address) the key first has to be removed and only after confirming the key removal email from the server, another upload is possible.

The key server will send out verification emails for all email addresses attached to a key. Lookup by email address will only succeed for emails that have been verified. You can choose to not verify all emails on the key in order to prevent that a key can be found by a certain email address. But the key server does not strip UserIDs from the key which are not verified, that means a successful lookup will always return the complete key as it was initially uploaded.

For key upload, lookup and removal: https://keys.mailvelope.com/demo.html
Please check also Spam folder for possible verification emails.

Email verification emails are sent out encrypted in order to not only verify that the user has access to the email account but also that they are in possession of the private key of the key that was uploaded to the key server. Verification emails are in PGP/MIME format. Should your webmail or other PGP-enabled mail client not be able to decrypt the email correctly the following workaround can be applied: download the encrypted.asc file attached to the verification email, open in text editor, copy the armored text and paste into email that you send to yourself. Use Mailvelope to decrypt the email and click on verification link.

**Comment by S3TH76** [comment]
The URL link from decripted file it gives me an error - "Invalid request.", when I access it.

**Comment by toberndo** [comment]
@S3TH76 I updated https://github.com/mailvelope/keyserver/issues/11#issuecomment-258122456 with explanations of error codes from the server.

**Comment by S3TH76** [comment]
You don't understand! I followed all steps correctly, until the phase where after I received the encrypted file and decrypt it with mailvelope add-on from Mozilla Firefox. 
When I access the url from decripted file for confirmation, I get an error message: "Invalid request!"

I'm curious if this service even function correctly....

![invalid_request-mailvelope](https://cloud.githubusercontent.com/assets/11060449/19970310/544d5a54-a1e4-11e6-84c9-6dee5840635b.JPG)

**Comment by eric1357a** [comment]
http://www.webatic.com/run/convert/qp.php
Just decode your url with that website and it will be fine.
Just tested a minute ago

**Comment by S3TH76** [comment]
nope! Still Invalid request. I attach the image with new decoded from quote-printable in UTF-8.
Observe that '3D' doesn't exist anymore after '=' !
![invalid_request-mailvelope-2](https://cloud.githubusercontent.com/assets/11060449/19971164/ed100aa0-a1e6-11e6-9b3f-2c1f87730b5d.JPG)

**Comment by toberndo** [comment]
@S3TH76 @eric1357a Problem is that line breaks in the URL must not be modified before decoding. I updated https://github.com/mailvelope/keyserver/issues/11#issuecomment-258122456 once again.

**Comment by eric1357a** [comment]
@toberndo I know and I already finish verification

**Comment by stonemirror** [comment]
Yeah, I ran into this issue as well. When the attachment is decrypted — I did this manually, GPGTools isn't working on macOS Sierra yet — it looks like this:

```
Content-Type: multipart/alternative;
 boundary="----sinikael-?=_1-14802753242610.15335576003417373"

------sinikael-?=_1-14802753242610.15335576003417373
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

Hello David Schlesinger,

please click here to verify your key:

https://keys.mailvelope.com/api/v1/key?op=3Dverify&keyId=3Daa42caa60faf27f1=
&nonce=3DNONCEWENTHERE
------sinikael-?=_1-14802753242610.15335576003417373
Content-Type: text/html
Content-Transfer-Encoding: quoted-printable

<p>Hello David Schlesinger,</p><p>please <a href=3D"https://keys.mailvelope=
.com/api/v1/key?op=3Dverify&keyId=3Daa42caa60faf27f1&nonce=3DNONCEWENTHERE">click here to verify</a> your key.=
</p>
------sinikael-?=_1-14802753242610.15335576003417373--
```

So, I've got a URL of

keys.mailvelope.com/api/v1/key?op=**3D**verify&keyId=**3D**aa42caa60faf27f1=
&nonce=**3D**NONCEWENTHERE

Note that in addition to the three errant instances of "3D", there's also an errant equal sign between the keyID value and the ampersand preceding the `nonce` keyword (which Markdown doesn't seem to want to allow me to make bold or italic or something...)

Took me a few minutes to sort this out, but the correct URL ends up being:

keys.mailvelope.com/api/v1/key?op=verify&keyId=aa42caa60faf27f1
&nonce=NONCEWENTHERE

**Comment by shuffle2** [comment]
There is nothing wrong with this output, the message is just encoded for email.
You can decode it with this:
```python
import email, sys

with open(sys.argv[1]) as f:
        m = email.message_from_string(f.read())
        if m.is_multipart():
                for p in m.get_payload():
                        print(p.get_payload(decode = True).decode('utf8'))
        else:
                print(m.get_payload(decode = True).decode('utf8'))
```
This is not a valid issue :p

**Comment by user-name-is-taken** [comment]
Not a developer on this project, just a user. When I tried to verify my key, the verification window appeared blank. Then I re-sized the window and everything appeared. Hope this helps.

**Comment by Undigon** [comment]
I ran into the same issue. I solved it using the online qp converter. I don't find it a satisfactory solution. This should not be an issue if the goal is to be "secure, easy" and "just as painless as modern messengers".

**Comment by toberndo** [comment]
Verification emails use now PGP/Inline with plaintext, therefore encoding issues of that kind should not arise anymore.
