### ISSUE TITLE
Where can i get the development.js file From?

### ISSUE THREAD

**Issue by klaus124431454** [mailvelope/keyserver#116]
Hi,

im attempting to deploy this in a selfhosted scenario and i cant find the development.js file can someone help me.

**Comment by stradarius** [comment]
Just use config/default.js as a template for config/development.js. Because development.js will only contain locally valid configuration settings, it has been set to be ignored by git.
Alternatively use environment variables instead, they have always priority over the config files.

I proposed an update to the README.md with pull request #118.

**Comment by klaus124431454** [comment]
OK thank you but the problem is that the program wont read the .env file but i fixt it so it isnt a problem anymore
