### ISSUE TITLE
can't find key from wingpg kleopatra

### ISSUE THREAD

**Issue by peterius** [mailvelope/keyserver#12]
I'm using keys.mailvelope.com hkp protocol, but it can't find my key even though the website interface works fine.

**Comment by shuffle2** [comment]
It seems windows gpg clients tend not to support `hkps://` (required by mailvelope/keyserver).  
I've only gotten it to work on bash-on-windows (essentially ubuntu), by `sudo apt-get install gnupg gnupg-curl`. The `gnupg-curl` add-on package is critical and transparently enables `hkps://` to work.  
The real issue is that gpg4win is just garbage, unfortunately.  
In any case this issue should be closed since it's not a problem with mailvelope/keyserver.

**Comment by toberndo** [comment]
@shuffle2 BTW, thanks for all the help with GitHub issues here. Much appreciated.
