### ISSUE TITLE
allow update of key expiry date

### ISSUE THREAD

**Issue by mdik** [mailvelope/keyserver#25]
Right now, in order to update a key's expiry date, you need to remove the key, and re-upload it with the new expiry-signatures.

It would be nice if the keyserver would detect these signatures, and update the key accordingly. User verification would not be required in my opinion as you need access to the private key in order to update the expiry date.

**Comment by shuffle2** [comment]
The point of requiring an email is to prove ownership/control of the **email account**. Control of the private key is taken for granted. I do not think bypassing the email validation should ever be allowed for the purposes of this project.

**Comment by mdik** [comment]
Yes, and ownership/contol of the email account was proven at the time of first upload. But I'd be happy with re-validation, too, if it keeps the code base simpler.

**Comment by kacf** [comment]
I think not allowing update of expiry is a severe limitation. My expiry date is updated often (which is a *good* thing), and there is no way I'm going to repeat the key signup process every time, especially since mailvelope's key server is not the only one in town.

Fully agree that email verification is great for *new* keys, but not for already verified ones that are just updated.

**Comment by toberndo** [comment]
Key update is now available.

**Comment by kacf** [comment]
:+1:
