### ISSUE TITLE
Option to disable sending mails at all?

### ISSUE THREAD

**Issue by nsauter** [mailvelope/keyserver#99]
Is there an option to disable sending mails at all? I dont want my keyserver to send mails whenever i import a key. Especially if the server is only for internal use and i won't inform every external user when i import his or her key to the server.

**Comment by nsauter** [comment]
So i only want the server to act as keychain where i can place keys and remove them. No interaction with the user (besides the gpg key gen upload). It that possible?

**Comment by abdazzamajhari** [comment]
> So i only want the server to act as keychain where i can place keys and remove them. No interaction with the user (besides the gpg key gen upload). It that possible?

did you success to create this server?

**Comment by abdazzamajhari** [comment]
because i dont understand, what i need to use, development.js or production.js

and where i put this variable to?

> NODE_ENV=production
MONGO_URI=127.0.0.1:27017/test_db
MONGO_USER=db_user
MONGO_PASS=db_password
SMTP_HOST=127.0.0.1
SMTP_PORT=465
SMTP_TLS=true
SMTP_STARTTLS=true
SMTP_PGP=true
SMTP_USER=smtp_user
SMTP_PASS=smtp_pass
SENDER_NAME="OpenPGP Key Server"
SENDER_EMAIL=noreply@example.com
HTTPS_UPGRADE=true (upgrade HTTP requests to HTTPS and use HSTS)
HTTPS_KEY_PIN=base64_encoded_sha256 (optional, see HPKP)
HTTPS_KEY_PIN_BACKUP=base64_encoded_sha256 (optional, see HPKP)

>

**Comment by nsauter** [comment]
> because i dont understand, what i need to use, development.js or production.js

I did manage to get it working, yes. But not with those files.

> 
> and where i put this variable to?
> 
> > NODE_ENV=production
> MONGO_URI=127.0.0.1:27017/test_db
> MONGO_USER=db_user
> MONGO_PASS=db_password

In my case i simply exported those as environment variables.

`export MONGO_PASS=password`

**Comment by abdazzamajhari** [comment]
> > because i dont understand, what i need to use, development.js or production.js
> 
> I did manage to get it working, yes. But not with those files.
> 
> > and where i put this variable to?
> > > NODE_ENV=production
> > > MONGO_URI=127.0.0.1:27017/test_db
> > > MONGO_USER=db_user
> > > MONGO_PASS=db_password
> 
> In my case i simply exported those as environment variables.
> 
> `export MONGO_PASS=password`

so, you exported those as environment variables? not creating a file and put it to development.js / production.js?

**Comment by toberndo** [comment]
The option to disable sending mails at all is not available. This would require to define keys as 'verified' directly after upload.
